Weapons:
  Ice Wand:
    Display Name: '&bIce Wand'
    Lore:
      - '&7Fire this at'
      - '&7your enemy to'
      - '&7slow them down'
    Velocity Multiplier: 1.8
    Cooldown (Ticks): 40
    Knockback: 0.2
