name: ScoreboardAPI
main: net.prospectmc.scoreboardapi.ScoreboredAPI
version: 0.1.0
author: zta192, Codisimus
commands:
  scoreboard:
    description: Used to toggle scoreboards
    usage: /<command> help
    aliases: [sb]
