name: AttributeAPI
main: net.prospectmc.attributeapi.AttributeAPI
version: 4.0.0
author: zta192, Codisimus
description: AttributeAPI.
commands:
  attribute:
    description: Used to apply attribute modifiers
    usage: /<command> help
    aliases: [att]
