name: AttributeAPI
main: com.zta192.AttributeAPI.AttributeAPI
version: 3.3.1
author: zta192, Codisimus
website: http://zta192.com
description: AttributeAPI.
commands:
  attribute:
    description: Used to apply attribute modifiers
    usage: /<command> help
    aliases: [att]
